include_guard(GLOBAL)

if (WIN32)
	set(__L_PLATFORM "Windows")
elseif (UNIX)
	if (APPLE)
		set(__L_PLATFORM "MacOS")
	else ()
		set(__L_PLATFORM "Linux")
	endif ()
else()
	project_message(STATUS "Unknown platform ${CMAKE_HOST_SYSTEM_NAME} for PaddlePaddle inference.")
endif ()

find_package(CUDAToolkit QUIET GLOBAL)

set(__L_SPECIFIC "cpu")
if (CUDAToolkit_FOUND)
	set(__L_NAME "cuda/${CUDAToolkit_VERSION_MAJOR}.${CUDAToolkit_VERSION_MINOR}")
	if (EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/vars/${__L_VERSION}/${__L_PLATFORM}/${__L_NAME}.cmake")
		set(__L_SPECIFIC "${__L_NAME}")
	endif ()
endif ()

project_message(STATUS "Using `${__L_SPECIFIC}` PaddlePaddle Inference.")
include("vars/${__L_VERSION}/${__L_PLATFORM}/${__L_SPECIFIC}.cmake" NO_POLICY_SCOPE)
