get_ext_version(freetype FREETYPE_VERSION)
get_ext_version(harfbuzz HARFBUZZ_VERSION)

list(APPEND __L_OPTIONS
	"-D" "FREETYPE_FOUND:BOOL=TRUE"
	"-D" "FREETYPE_INCLUDE_DIRS:STRING=${CMAKE_INSTALL_PREFIX}/include/freetype2"
	"-D" "FREETYPE_VERSION:STRING=${FREETYPE_VERSION}"
	"-D" "FREETYPE_VERSION_STRING:STRING=${FREETYPE_VERSION}"
	"-D" "HARFBUZZ_FOUND:BOOL=TRUE"
	"-D" "HARFBUZZ_INCLUDE_DIRS:STRING=${CMAKE_INSTALL_PREFIX}/include/harfbuzz"
	"-D" "HARFBUZZ_VERSION:STRING=${HARFBUZZ_VERSION}"
	"-D" "HARFBUZZ_VERSION_STRING:STRING=${HARFBUZZ_VERSION}"
)
