set(onnxruntime_USE_CUDA ON)
set(onnxruntime_BUILD_UNIT_TESTS OFF)
set(onnxruntime_USE_AVX ON)
set(onnxruntime_USE_AVX2 ON)
set(onnxruntime_BUILD_SHARED_LIB ON)
set(onnxruntime_ENABLE_LTO ON)
set(onnxruntime_USE_FULL_PROTOBUF OFF)
set(onnxruntime_DISABLE_RTTI ON)

set(__F_SUBMODULE_PATH "${__F_SUBMODULE}/cmake")
