project(sqlite3
	VERSION "@__L_VERSION@"
	HOMEPAGE_URL "https://www.sqlite.org"
	LANGUAGES
		C
)

file(COPY
	"sqlite3.h"
	DESTINATION "${CMAKE_CURRENT_SOURCE_DIR}/include"
)
file(COPY
	"sqlite3.c"
	DESTINATION "${CMAKE_CURRENT_SOURCE_DIR}/src"
)
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/userauth.c" __L_USERAUTH_C)
file(APPEND "${CMAKE_CURRENT_SOURCE_DIR}/src/sqlite3.c" "${__L_USERAUTH_C}")

add_library(sqlite3 STATIC
	"src/sqlite3.c"
	"src/sqlite3async.c"
	"src/sqlite3expert.c"
	# "src/sqlite3rbu.c"
)
add_library(sqlite3::sqlite3 ALIAS sqlite3)

target_compile_definitions(sqlite3
	PUBLIC
		"SQLITE_ENABLE_ASYNCIO"
		"SQLITE_ENABLE_ATOMIC_WRITE"
		"SQLITE_ENABLE_BATCH_ATOMIC_WRITE"
		"SQLITE_ENABLE_CEROD=2"
		"SQLITE_ENABLE_FTS3_PARENTHESIS"
		"SQLITE_ENABLE_FTS4"
		"SQLITE_ENABLE_FTS5"
		"SQLITE_ENABLE_GEOPOLY"
		"SQLITE_ENABLE_HIDDEN_COLUMNS"
		"SQLITE_ENABLE_MATH_FUNCTIONS"
		"SQLITE_ENABLE_MEMORY_MANAGEMENT"
		"SQLITE_ENABLE_MEMSYS5"
		"SQLITE_ENABLE_NORMALIZE"
		"SQLITE_ENABLE_PREUPDATE_HOOK"
		"SQLITE_ENABLE_RBU"
		"SQLITE_ENABLE_RTREE"
		"SQLITE_ENABLE_SESSION"
		"SQLITE_ENABLE_SNAPSHOT"
		"SQLITE_ENABLE_UNLOCK_NOTIFY"
		"SQLITE_USE_ALLOCA"
		"SQLITE_USER_AUTHENTICATION"
)
if (WIN32)
	target_compile_definitions(sqlite3
		PUBLIC
			"SQLITE_WIN32_MALLOC"
	)
endif ()
target_include_directories(sqlite3
	PUBLIC
		"include"
)
