macro (create_component_options NAME DISPLAY_NAME)
	list(APPEND PROJECT_DEFINED_COMPONENTS "${NAME}")

	string(TOUPPER "${NAME}" NAME_UPPER)
	option(${PROJECT_OPTIONS_PREFIX}_BUILD_${NAME_UPPER} "Build ${DISPLAY_NAME}." $<BOOL:${${PROJECT_OPTIONS_PREFIX}_BUILD_ALL}>)
	cmake_dependent_option(${PROJECT_OPTIONS_PREFIX}_BUILD_${NAME_UPPER}_SHARED "Build ${DISPLAY_NAME} shared library." $<BOOL:${${PROJECT_OPTIONS_PREFIX}_BUILD_SHARED}> "${PROJECT_OPTIONS_PREFIX}_BUILD_${NAME_UPPER}" ON)
endmacro ()
